In [2]:
import numpy as np

In [3]:
state = {
    0 : "Yash Khanna",
    1 : "Harsh Gujarathi",
    2 : "Vaibhav"
}
state

{0: 'Yash Khanna', 1: 'Harsh Gujarathi', 2: 'Vaibhav'}

In [4]:
A = np.array([[0.0, 0.5, 0.5], [0.3, 0.0, 0.7], [0.5, 0.5, 0.0]])
A

array([[0. , 0.5, 0.5],
       [0.3, 0. , 0.7],
       [0.5, 0.5, 0. ]])

In [5]:
n = 15
start_state = 0
curr_state = start_state
print(state[curr_state], "--->", end=" ")

while n-1:
    curr_state = np.random.choice([0, 1, 2], p=A[curr_state])
    print(state[curr_state], "--->", end=" ")
    n-=1
print("stop")

Yash Khanna ---> Harsh Gujarathi ---> Vaibhav ---> Harsh Gujarathi ---> Vaibhav ---> Harsh Gujarathi ---> Vaibhav ---> Yash Khanna ---> Harsh Gujarathi ---> Vaibhav ---> Yash Khanna ---> Harsh Gujarathi ---> Vaibhav ---> Yash Khanna ---> Vaibhav ---> stop


In [6]:
steps = 10**6
start_state = 0
curr_state = start_state
pi = np.array([0, 0, 0])
pi[start_state] = 1

i = 0
while i<steps:
    curr_state = np.random.choice([0,1,2], p=A[curr_state])
    pi[curr_state]+=1
    i +=1

print("π = ", pi/steps)

π =  [0.28885  0.332915 0.378236]


In [7]:
steps = 10**3
A_n = A

i=0
while i<steps:
    A_n =  np.matmul(A_n, A)
    i+=1

print("A^n = \n", A_n, "\n")
print("π = ", A_n[0])

A^n = 
 [[0.28888889 0.33333333 0.37777778]
 [0.28888889 0.33333333 0.37777778]
 [0.28888889 0.33333333 0.37777778]] 

π =  [0.28888889 0.33333333 0.37777778]


In [8]:
import scipy.linalg
values, left = scipy.linalg.eig(A, right = False, left = True)

print("left eigen vectors = \n", left, "\n")
print("eigen values = \n", values)

left eigen vectors = 
 [[ 4.97431176e-01+0.00000000e+00j -7.07106781e-01+1.47115583e-08j
  -7.07106781e-01-1.47115583e-08j]
 [ 5.73959049e-01+0.00000000e+00j  3.24440742e-17-1.47115583e-08j
   3.24440742e-17+1.47115583e-08j]
 [ 6.50486922e-01+0.00000000e+00j  7.07106781e-01+0.00000000e+00j
   7.07106781e-01-0.00000000e+00j]] 

eigen values = 
 [ 1. +0.00000000e+00j -0.5+4.16105706e-09j -0.5-4.16105706e-09j]


In [9]:
pi = left[:,0]
pi_normalized = [(x/np.sum(pi)).real for x in pi]
pi_normalized

[0.28888888888888875, 0.33333333333333337, 0.3777777777777779]

In [10]:
def find_prob(seq, A, pi):
    start_state = seq[0]
    prob = pi[start_state]
    prev_state, curr_state = start_state, start_state
    for i in range(1, len(seq)):
        curr_state = seq[i]
        prob *= A[prev_state][curr_state]
        prev_state = curr_state
    return prob

print(find_prob([1, 2, 2, 0], A, pi_normalized))

0.0
